-- AlterTable: Add SSIM and PSNR columns to Benchmark
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "ssim" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "psnr" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "ssimSamples" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "ssimSum" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "psnrSamples" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "psnrSum" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable: Add SSIM and PSNR columns to Submission
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "ssim" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "psnr" DOUBLE PRECISION;
