"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useVirtualizer } from "@tanstack/react-virtual";
import type { Benchmark } from "../lib/types";
import { WORKBENCH_PAGE_SIZE, buildWorkbenchSearchString, type EncoderTypeFilter, type WorkbenchSearchState, type WorkbenchSortKey } from "../lib/queryState";
import ComparePanel, { CompareStickyBar } from "./ComparePanel";
import styles from "./BenchmarksTable.module.css";

export type { Benchmark } from "../lib/types";

const columns = "42px minmax(205px,2.1fr) minmax(140px,1.35fr) minmax(190px,1.8fr) 90px 90px 112px 115px 88px 74px";
const formatSize=(n:number)=>n >= 1024*1024 ? `${(n/(1024*1024)).toFixed(1)} MB` : `${Math.round(n/1024)} KB`;
const samples=(row:Benchmark)=>row.sampleCount ?? row.samples ?? 1;
const value=(n:number|null|undefined, digits=1)=>n == null ? "—" : n.toFixed(digits);

export default function BenchmarksTable({initialData,totalCount,currentPage}:{initialData:Benchmark[];totalCount:number;currentPage:number}) {
  const router=useRouter(), pathname=usePathname()??"/", params=useSearchParams();
  const initial=useMemo<WorkbenchSearchState>(()=>({page:currentPage,cpu:params.get("cpu")||"",gpu:params.get("gpu")||"",codec:params.get("codec")||"",preset:params.get("preset")||"",sort:(params.get("sort") as WorkbenchSortKey)||"",dir:params.get("dir")==="asc"?"asc":"desc",encoderType:(params.get("encoderType") as EncoderTypeFilter)||""}),[currentPage,params]);
  const [state,setState]=useState(initial), [selected,setSelected]=useState<Set<string>>(new Set()), [details,setDetails]=useState<Benchmark|null>(null), [compare,setCompare]=useState(false), [myHardware,setMyHardware]=useState(false), [hardwareOpen,setHardwareOpen]=useState(false);
  const first=useRef(true);
  useEffect(()=>{ if(first.current){first.current=false;return;} const timer=setTimeout(()=>{const q=buildWorkbenchSearchString(state);router.replace(q?`${pathname}?${q}`:pathname,{scroll:false});},240);return()=>clearTimeout(timer);},[state,pathname,router]);
  useEffect(()=>{try{setMyHardware(localStorage.getItem("encodingdb-my-hardware")!==null)}catch{/* Storage is optional. */}},[]);
  const update=(key:keyof WorkbenchSearchState, value:string|number)=>setState(s=>({...s,[key]:value,page:key==="page"?Number(value):1}));
  const rows=useMemo(()=>myHardware ? initialData.filter(row=>{try{const raw=localStorage.getItem("encodingdb-my-hardware");const pref=raw?JSON.parse(raw):{};return (!pref.gpu||row.gpuModel?.toLowerCase().includes(pref.gpu.toLowerCase()))&&(!pref.cpu||row.cpuModel.toLowerCase().includes(pref.cpu.toLowerCase()));}catch{return true}}) : initialData,[initialData,myHardware]);
  const toggle=useCallback((id:string)=>setSelected(old=>{const next=new Set(old);if(next.has(id))next.delete(id);else if(next.size<4)next.add(id);return next;}),[]);
  const setSort=(key:WorkbenchSortKey)=>setState(s=>({ ...s,sort:key,dir:s.sort===key&&s.dir==="desc"?"asc":"desc",page:1 }));
  const clear=()=>{setSelected(new Set());setCompare(false);};
  const selectedRows=rows.filter(row=>selected.has(row.id));
  return <section className={styles.section} aria-label="Benchmark results">
    <div className={styles.controls}>
      <label className={styles.search}><span className="srOnly">Search benchmark corpus</span><input className="input" placeholder="Search hardware, encoder, codec, preset, or result…" value={state.codec} onChange={e=>update("codec",e.target.value)} /></label>
      <select aria-label="Hardware vendor" className="input" value={state.encoderType} onChange={e=>update("encoderType",e.target.value)}><option value="">All encoders</option><option value="hardware">Hardware encoders</option><option value="software">Software encoders</option></select>
      <input aria-label="Filter CPU" className="input" placeholder="CPU" value={state.cpu} onChange={e=>update("cpu",e.target.value)} />
      <input aria-label="Filter GPU" className="input" placeholder="GPU" value={state.gpu} onChange={e=>update("gpu",e.target.value)} />
      <input aria-label="Filter preset" className="input" placeholder="Preset" value={state.preset} onChange={e=>update("preset",e.target.value)} />
      <button className="btn" onClick={()=>setHardwareOpen(true)}>My Hardware{myHardware?" · on":""}</button>
      <button className="btn" onClick={()=>setState({page:1,cpu:"",gpu:"",codec:"",preset:"",sort:"",dir:"desc",encoderType:""})}>Clear filters</button>
    </div>
    <div className={styles.tableMeta}><span>{totalCount.toLocaleString()} public results</span><span>Choose up to 4 rows to compare</span></div>
    <VirtualTable rows={rows} selected={selected} toggle={toggle} onDetails={setDetails} sort={state.sort} dir={state.dir} setSort={setSort}/>
    <div className={styles.pagination}><span>Page {state.page} of {Math.max(1,Math.ceil(totalCount/WORKBENCH_PAGE_SIZE))}</span><div><button className="btn" disabled={state.page<=1} onClick={()=>update("page",state.page-1)}>Previous</button><button className="btn" disabled={state.page>=Math.ceil(totalCount/WORKBENCH_PAGE_SIZE)} onClick={()=>update("page",state.page+1)}>Next</button></div></div>
    <CompareStickyBar count={selected.size} onCompare={()=>setCompare(true)} onClear={clear}/>
    {details&&<Details row={details} close={()=>setDetails(null)}/>} {compare&&selected.size>=2&&<ComparePanel rows={selectedRows} onClose={()=>setCompare(false)} onClear={clear}/>} {hardwareOpen&&<MyHardware close={()=>setHardwareOpen(false)} enabled={myHardware} setEnabled={setMyHardware}/>} 
  </section>;
}

function VirtualTable({rows,selected,toggle,onDetails,sort,dir,setSort}:{rows:Benchmark[];selected:Set<string>;toggle:(id:string)=>void;onDetails:(row:Benchmark)=>void;sort:WorkbenchSortKey;dir:"asc"|"desc";setSort:(key:WorkbenchSortKey)=>void}) { const ref=useRef<HTMLDivElement>(null);const v=useVirtualizer({count:rows.length,getScrollElement:()=>ref.current,estimateSize:()=>56,overscan:8});const head=(name:string,key:WorkbenchSortKey,cls="")=><button className={`${styles.headButton} ${cls}`} onClick={()=>setSort(key)} aria-sort={sort===key?(dir==="asc"?"ascending":"descending"):"none"}>{name}{sort===key?(dir==="asc"?" ↑":" ↓"):""}</button>;return <div className={styles.tableWrap}><div className={styles.gridHeader} style={{"--columns":columns} as React.CSSProperties}><span/><span>{head("Hardware","gpuModel")}</span><span>{head("Encoder","codec")}</span><span>{head("Configuration","preset")}</span><span>{head("FPS","fps",styles.right)}</span><span>{head("VMAF","vmaf",styles.right)}</span><span>{head("Output size","fileSizeBytes",styles.right)}</span><span>{head("Avg. power","gpuPowerAvgW",styles.right)}</span><span>{head("Samples","sampleCount",styles.right)}</span><span>Details</span></div><div ref={ref} className={styles.scroller} role="table"><div style={{height:v.getTotalSize(),position:"relative"}}>{v.getVirtualItems().map(item=>{const row=rows[item.index];return <div key={row.id} className={`${styles.row} ${selected.has(row.id)?styles.selected:""}`} style={{"--columns":columns,height:item.size,transform:`translateY(${item.start}px)`} as React.CSSProperties} role="row"><span><input type="checkbox" aria-label={`Select ${row.id} for comparison`} checked={selected.has(row.id)} disabled={!selected.has(row.id)&&selected.size>=4} onChange={()=>toggle(row.id)}/></span><span><strong>{row.gpuModel||row.cpuModel}</strong><small>{row.gpuModel?row.cpuModel:row.os}</small></span><span><strong>{row.encoderName||row.codec}</strong><small>{row.codec}</small></span><span><span className="mono">{row.preset}{row.crf==null?"":` · CRF ${row.crf}`}</span><small>{row.ffmpegVersion||"FFmpeg version not reported"}</small></span><span className="numeric">{value(row.fps,2)}</span><span className="numeric">{value(row.vmaf)}</span><span className="numeric">{formatSize(row.fileSizeBytes)}</span><span className="numeric">{row.gpuPowerAvgW==null?"—":`${value(row.gpuPowerAvgW)} W`}</span><span>{samples(row)<3?<em className={styles.lowSample}>{samples(row)}</em>:samples(row)}</span><span><button className={styles.detail} onClick={()=>onDetails(row)}>View</button></span></div>})}{rows.length===0&&<div className={styles.empty}>No verified runs match these filters. <button className={styles.inlineButton} onClick={()=>location.assign("/run")}>Run a benchmark</button></div>}</div></div></div> }
function Details({row,close}:{row:Benchmark;close:()=>void}) {return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="result-title" onMouseDown={e=>e.target===e.currentTarget&&close()}><article className="modal"><header className="modal-header"><div><strong id="result-title">Run details</strong><div className="subtle">Public benchmark provenance</div></div><button className="btn" onClick={close}>Close</button></header><div className={styles.detailBody}><div className={styles.metricGrid}><Metric n="FPS" v={value(row.fps,2)}/><Metric n="VMAF" v={value(row.vmaf)}/><Metric n="Output size" v={formatSize(row.fileSizeBytes)}/><Metric n="Average power" v={row.gpuPowerAvgW==null?"Not reported":`${value(row.gpuPowerAvgW)} W`}/></div><dl className={styles.provenance}><Dt n="Hardware" v={`${row.gpuModel||"No GPU reported"} · ${row.cpuModel}`}/><Dt n="Encoder" v={row.encoderName||row.codec}/><Dt n="Configuration" v={`${row.preset}${row.crf==null?"":` · CRF ${row.crf}`}`}/><Dt n="FFmpeg" v={row.ffmpegVersion||"Not reported"}/><Dt n="Operating system" v={row.os}/><Dt n="Input checksum" v={row.inputHash||"Not reported"}/><Dt n="Sample count" v={String(samples(row))}/><Dt n="SSIM / PSNR" v={`${value(row.ssim,4)} / ${value(row.psnr,2)}`}/><Dt n="Memory peak" v={row.peakMemoryMB==null?"Not reported":`${Math.round(row.peakMemoryMB)} MB`}/></dl></div></article></div>}
const Metric=({n,v}:{n:string;v:string})=><div><dt>{n}</dt><dd className="numeric">{v}</dd></div>;const Dt=({n,v}:{n:string;v:string})=><><dt>{n}</dt><dd>{v}</dd></>;
function MyHardware({close,enabled,setEnabled}:{close:()=>void;enabled:boolean;setEnabled:(x:boolean)=>void}) {const [gpu,setGpu]=useState(""),[cpu,setCpu]=useState("");useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("encodingdb-my-hardware")||"{}");setGpu(p.gpu||"");setCpu(p.cpu||"")}catch{/* Storage is optional. */}},[]);const save=()=>{try{if(gpu||cpu){localStorage.setItem("encodingdb-my-hardware",JSON.stringify({gpu,cpu}));setEnabled(true)}else{localStorage.removeItem("encodingdb-my-hardware");setEnabled(false)}}catch{/* Storage is optional. */}close()};return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="hardware-title"><div className="modal"><header className="modal-header"><strong id="hardware-title">My Hardware</strong><button className="btn" onClick={close}>Close</button></header><div className={styles.hardwareForm}><p className="subtle">Stored only in this browser to filter the public dataset.</p><label>GPU<input className="input" value={gpu} onChange={e=>setGpu(e.target.value)} placeholder="e.g. RTX 4070"/></label><label>CPU<input className="input" value={cpu} onChange={e=>setCpu(e.target.value)} placeholder="e.g. Ryzen 7950X"/></label><button className="btn btn-primary" onClick={save}>{enabled?"Update hardware":"Filter to my hardware"}</button></div></div></div>}
