export const WORKBENCH_PAGE_SIZE = 50;
export type WorkbenchSortKey = "cpuModel" | "gpuModel" | "codec" | "preset" | "fps" | "vmaf" | "fileSizeBytes" | "gpuPowerAvgW" | "sampleCount" | "";
export type EncoderTypeFilter = "" | "hardware" | "software";
export type WorkbenchSearchState = { page:number; cpu:string; gpu:string; codec:string; preset:string; sort:WorkbenchSortKey; dir:"asc"|"desc"; encoderType:EncoderTypeFilter };
export type AnalyticsSearchState = { contentClass:string; resolution:string; crf:number; minSamples:number };
type Params = { get(name:string):string|null };
const sortKeys: WorkbenchSortKey[] = ["cpuModel","gpuModel","codec","preset","fps","vmaf","fileSizeBytes","gpuPowerAvgW","sampleCount",""];
const positive = (value:string|null, fallback:number) => value && /^\d+$/.test(value) && Number(value)>0 ? Number(value) : fallback;
export function parseWorkbenchSearchParams(params:Params):WorkbenchSearchState { const sort=params.get("sort") as WorkbenchSortKey; const type=params.get("encoderType"); return { page:positive(params.get("page"),1), cpu:params.get("cpu")||"", gpu:params.get("gpu")||"", codec:params.get("codec")||"", preset:params.get("preset")||"", sort:sortKeys.includes(sort)?sort:"", dir:params.get("dir")==="asc"?"asc":"desc", encoderType:type==="hardware"||type==="software"?type:"" }; }
export function buildWorkbenchSearchString(state:WorkbenchSearchState):string { const p=new URLSearchParams(); if(state.page>1)p.set("page",String(state.page)); (["cpu","gpu","codec","preset"] as const).forEach(k=>state[k]&&p.set(k,state[k])); if(state.sort)p.set("sort",state.sort); if(state.dir!=="desc")p.set("dir",state.dir); if(state.encoderType)p.set("encoderType",state.encoderType); return p.toString(); }
export function parseAnalyticsSearchParams(params:Params):AnalyticsSearchState { return { contentClass:params.get("contentClass")||"mixed",resolution:params.get("resolution")||"1080p",crf:positive(params.get("crf"),24),minSamples:positive(params.get("minSamples"),3) }; }
export function buildAnalyticsSearchString(state:AnalyticsSearchState):string { const p=new URLSearchParams(); if(state.contentClass!=="mixed")p.set("contentClass",state.contentClass);if(state.resolution!=="1080p")p.set("resolution",state.resolution);if(state.crf!==24)p.set("crf",String(state.crf));if(state.minSamples!==3)p.set("minSamples",String(state.minSamples));return p.toString(); }
