-- Sprint 6: Hardware Intelligence
-- Add hardware metrics fields to Benchmark and Submission models

-- Benchmark: hardware metric columns
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuUtilAvg" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuPowerAvgW" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuMemPeakMB" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "cpuUtilAvg" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "cpuUtilMax" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "peakMemoryMB" DOUBLE PRECISION;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "thermalThrottle" BOOLEAN;

-- Benchmark: hardware metrics aggregation columns
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuUtilSamples" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuUtilSum" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuPowerSamples" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "gpuPowerSum" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "cpuUtilSamples" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "cpuUtilSum" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Benchmark" ADD COLUMN IF NOT EXISTS "peakMemoryMax" DOUBLE PRECISION;

-- Submission: hardware metric columns
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "gpuUtilAvg" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "gpuPowerAvgW" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "gpuMemPeakMB" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "cpuUtilAvg" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "cpuUtilMax" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "peakMemoryMB" DOUBLE PRECISION;
ALTER TABLE "Submission" ADD COLUMN IF NOT EXISTS "thermalThrottle" BOOLEAN;
