const now = new Date().toISOString();

export const MOCK_QUERY_ROWS = [
  {
    id: "mock-1",
    createdAt: now,
    cpuModel: "Intel Core i7-12700K",
    gpuModel: "NVIDIA GeForce RTX 3060",
    ramGB: 32,
    os: "Windows 11",
    codec: "h264_nvenc",
    codecFamily: "h264",
    crf: 24,
    preset: "p6",
    fps: 120.5,
    vmaf: 95.2,
    ssim: 0.9811,
    psnr: 41.8,
    fileSizeBytes: 85 * 1024 * 1024,
    notes: null,
    ffmpegVersion: "5.1",
    encoderName: "h264_nvenc",
    clientVersion: "1.0.0",
    inputHash: null,
    runMs: 10000,
    status: "accepted",
    samples: 3,
    vmafSamples: 3,
    ssimSamples: 3,
    psnrSamples: 3,
    gpuPowerAvgW: 160.4,
    cpuUtilAvg: 74.5,
    cpuUtilMax: 89.2,
    peakMemoryMB: 1140,
    thermalThrottle: false,
    fpsPerWatt: 0.75,
    qualityPerWatt: 0.59,
  },
  {
    id: "mock-2",
    createdAt: now,
    cpuModel: "Apple M2",
    gpuModel: "",
    ramGB: 16,
    os: "macOS 15",
    codec: "hevc_videotoolbox",
    codecFamily: "hevc",
    crf: 24,
    preset: "medium",
    fps: 80.2,
    vmaf: 92.4,
    ssim: 0.9725,
    psnr: 39.6,
    fileSizeBytes: 70 * 1024 * 1024,
    notes: null,
    ffmpegVersion: "6.0",
    encoderName: "hevc_videotoolbox",
    clientVersion: "1.0.0",
    inputHash: null,
    runMs: 12000,
    status: "accepted",
    samples: 3,
    vmafSamples: 3,
    ssimSamples: 3,
    psnrSamples: 3,
    gpuPowerAvgW: 48.5,
    cpuUtilAvg: 59.1,
    cpuUtilMax: 71.2,
    peakMemoryMB: 860,
    thermalThrottle: false,
    fpsPerWatt: 1.65,
    qualityPerWatt: 1.91,
  },
];

export function buildMockLeaderboards() {
  return [
    {
      encoderName: "h264_nvenc",
      codecFamily: "h264",
      preset: "p6",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 120.5,
      avgVmaf: 95.2,
      avgSsim: 0.9811,
      avgPsnr: 41.8,
      avgSizeBytes: 85 * 1024 * 1024,
      avgPowerW: 160.4,
      fpsPerWatt: 0.75,
      qualityPerWatt: 0.59,
      plScore: 82.1,
    },
    {
      encoderName: "hevc_videotoolbox",
      codecFamily: "hevc",
      preset: "medium",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 80.2,
      avgVmaf: 92.4,
      avgSsim: 0.9725,
      avgPsnr: 39.6,
      avgSizeBytes: 70 * 1024 * 1024,
      avgPowerW: 48.5,
      fpsPerWatt: 1.65,
      qualityPerWatt: 1.91,
      plScore: 87.4,
    },
  ];
}

export function buildMockHardware() {
  return [
    {
      cpuModel: "Apple M2",
      gpuModel: "",
      encoderName: "hevc_videotoolbox",
      codecFamily: "hevc",
      preset: "medium",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 80.2,
      avgVmaf: 92.4,
      avgPowerW: 48.5,
      fpsPerWatt: 1.65,
      score: 0.93,
    },
    {
      cpuModel: "Intel Core i7-12700K",
      gpuModel: "NVIDIA GeForce RTX 3060",
      encoderName: "h264_nvenc",
      codecFamily: "h264",
      preset: "p6",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 120.5,
      avgVmaf: 95.2,
      avgPowerW: 160.4,
      fpsPerWatt: 0.75,
      score: 0.76,
    },
  ];
}

export function buildMockEncoders() {
  return [
    {
      encoderName: "h264_nvenc",
      codecFamily: "h264",
      preset: "p6",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 120.5,
      avgVmaf: 95.2,
      avgSsim: 0.9811,
      avgPsnr: 41.8,
      avgSizeBytes: 85 * 1024 * 1024,
    },
    {
      encoderName: "hevc_videotoolbox",
      codecFamily: "hevc",
      preset: "medium",
      crf: 24,
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 80.2,
      avgVmaf: 92.4,
      avgSsim: 0.9725,
      avgPsnr: 39.6,
      avgSizeBytes: 70 * 1024 * 1024,
    },
  ];
}
