const now = new Date().toISOString();

export const MOCK_QUERY_ROWS = [
  {
    id: "mock-1",
    createdAt: now,
    cpuModel: "Intel Core i7-12700K",
    gpuModel: "NVIDIA GeForce RTX 3060",
    ramGB: 32,
    os: "Windows 11",
    codec: "h264_nvenc",
    codecFamily: "h264",
    crf: 24,
    preset: "p6",
    fps: 120.5,
    vmaf: 95.2,
    ssim: 0.9811,
    psnr: 41.8,
    fileSizeBytes: 85 * 1024 * 1024,
    notes: null,
    ffmpegVersion: "5.1",
    encoderName: "h264_nvenc",
    clientVersion: "1.0.0",
    inputHash: null,
    runMs: 10000,
    status: "accepted",
    samples: 3,
    vmafSamples: 3,
    ssimSamples: 3,
    psnrSamples: 3,
    gpuPowerAvgW: 160.4,
    cpuUtilAvg: 74.5,
    cpuUtilMax: 89.2,
    peakMemoryMB: 1140,
    thermalThrottle: false,
    fpsPerWatt: 0.75,
    qualityPerWatt: 0.59,
  },
  {
    id: "mock-2",
    createdAt: now,
    cpuModel: "Apple M2",
    gpuModel: "",
    ramGB: 16,
    os: "macOS 15",
    codec: "hevc_videotoolbox",
    codecFamily: "hevc",
    crf: 24,
    preset: "medium",
    fps: 80.2,
    vmaf: 92.4,
    ssim: 0.9725,
    psnr: 39.6,
    fileSizeBytes: 70 * 1024 * 1024,
    notes: null,
    ffmpegVersion: "6.0",
    encoderName: "hevc_videotoolbox",
    clientVersion: "1.0.0",
    inputHash: null,
    runMs: 12000,
    status: "accepted",
    samples: 3,
    vmafSamples: 3,
    ssimSamples: 3,
    psnrSamples: 3,
    gpuPowerAvgW: 48.5,
    cpuUtilAvg: 59.1,
    cpuUtilMax: 71.2,
    peakMemoryMB: 860,
    thermalThrottle: false,
    fpsPerWatt: 1.65,
    qualityPerWatt: 1.91,
  },
];

export function buildMockLeaderboards() {
  const profiles = {
    balanced: { mode: "balanced", label: "Balanced", weights: { quality: 0.5, bitrate: 0.3, speed: 0.2 }, constraints: { minimumQuality: 90, minimumRealtimeRatio: 1, requireRecommendationEligibility: false } },
    quality: { mode: "quality", label: "Quality", weights: { quality: 0.72, bitrate: 0.1, speed: 0.18 }, constraints: { minimumQuality: 94, minimumRealtimeRatio: 0.75, requireRecommendationEligibility: false } },
    storage: { mode: "storage", label: "Storage", weights: { quality: 0.28, bitrate: 0.56, speed: 0.16 }, constraints: { minimumQuality: 90, maximumBitrateBps: 5_000_000, requireRecommendationEligibility: false } },
    realtime: { mode: "realtime", label: "Realtime", weights: { quality: 0.2, bitrate: 0.1, speed: 0.7 }, constraints: { minimumQuality: 88, minimumRealtimeRatio: 1, requireRecommendationEligibility: false } },
    custom: { mode: "custom", label: "Custom", weights: { quality: 0.5, bitrate: 0.3, speed: 0.2 }, constraints: { minimumQuality: 90, minimumRealtimeRatio: 1, requireRecommendationEligibility: false } },
  } as const;

  const fitModes = (scores: Record<string, number | null>, ranks: Record<string, number>, eligible: Record<string, boolean>, reasons?: Partial<Record<string, string[]>>) => ({
    balanced: { mode: "balanced", label: "Balanced", eligible: eligible.balanced, score: scores.balanced, rank: ranks.balanced, reasons: reasons?.balanced ?? [], weights: profiles.balanced.weights, constraints: { minimumQuality: { passed: true, required: 90, actual: 94.7, reason: null }, minimumRealtimeRatio: { passed: true, required: 1, actual: 4.1, reason: null }, maximumBitrateBps: { passed: true, required: null, actual: 4_800_000, reason: null }, compatibility: { passed: true, required: null, actual: "hevc", reason: null }, recommendationEligibility: { passed: true, required: false, actual: true, reason: null } } },
    quality: { mode: "quality", label: "Quality", eligible: eligible.quality, score: scores.quality, rank: ranks.quality, reasons: reasons?.quality ?? [], weights: profiles.quality.weights, constraints: { minimumQuality: { passed: true, required: 94, actual: 94.7, reason: null }, minimumRealtimeRatio: { passed: true, required: 0.75, actual: 4.1, reason: null }, maximumBitrateBps: { passed: true, required: null, actual: 4_800_000, reason: null }, compatibility: { passed: true, required: null, actual: "hevc", reason: null }, recommendationEligibility: { passed: true, required: false, actual: true, reason: null } } },
    storage: { mode: "storage", label: "Storage", eligible: eligible.storage, score: scores.storage, rank: ranks.storage, reasons: reasons?.storage ?? [], weights: profiles.storage.weights, constraints: { minimumQuality: { passed: true, required: 90, actual: 94.7, reason: null }, minimumRealtimeRatio: { passed: true, required: null, actual: 4.1, reason: null }, maximumBitrateBps: { passed: true, required: 5_000_000, actual: 4_800_000, reason: null }, compatibility: { passed: true, required: null, actual: "hevc", reason: null }, recommendationEligibility: { passed: true, required: false, actual: true, reason: null } } },
    realtime: { mode: "realtime", label: "Realtime", eligible: eligible.realtime, score: scores.realtime, rank: ranks.realtime, reasons: reasons?.realtime ?? [], weights: profiles.realtime.weights, constraints: { minimumQuality: { passed: true, required: 88, actual: 94.7, reason: null }, minimumRealtimeRatio: { passed: true, required: 1, actual: 4.1, reason: null }, maximumBitrateBps: { passed: true, required: null, actual: 4_800_000, reason: null }, compatibility: { passed: true, required: null, actual: "hevc", reason: null }, recommendationEligibility: { passed: true, required: false, actual: true, reason: null } } },
    custom: { mode: "custom", label: "Custom", eligible: eligible.custom, score: scores.custom, rank: ranks.custom, reasons: reasons?.custom ?? [], weights: profiles.custom.weights, constraints: { minimumQuality: { passed: true, required: 90, actual: 94.7, reason: null }, minimumRealtimeRatio: { passed: true, required: 1, actual: 4.1, reason: null }, maximumBitrateBps: { passed: true, required: null, actual: 4_800_000, reason: null }, compatibility: { passed: true, required: null, actual: "hevc", reason: null }, recommendationEligibility: { passed: true, required: false, actual: true, reason: null } } },
  });

  const makeRow = (rowId: string, encoderName: string, codecFamily: "h264" | "hevc" | "av1" | "vp9" | "other", preset: string, avgFps: number, avgVmaf: number, avgVmafP5: number, avgVideoBitrateBps: number, plScore: number, components: { quality: number; bitrate: number; speed: number }, recommended: boolean, modes: ReturnType<typeof fitModes>, overrides?: Record<string, unknown>) => ({
    rowId,
    encoderName,
    codecFamily,
    preset,
    rateControl: {
      requestedMode: "CONSTANT_QUALITY",
      effectiveMode: "CONSTANT_QUALITY",
      qualityValue: 24,
      targetBitrateKbps: null,
      maxBitrateKbps: null,
      bufferSizeKbits: null,
      label: "CONSTANT_QUALITY 24",
    },
    contentClass: "mixed",
    resolution: "1080p",
    passes: 1,
    workloadId: "mixed-1080p",
    hardwareKey: "apple-m2-hevc",
    hardwareLabel: "Apple M2 / CPU-only / macOS 15",
    realtimeRatio: avgFps / 30,
    effectiveQuality: (avgVmaf * 0.85) + (avgVmafP5 * 0.15),
    scoreFormulaVersion: "7.0",
    benchmarkProtocolVersion: "benchmark-protocol-v1",
    sourceSuiteVersion: "encodingdb-test-suite-v1",
    qualityModelId: "vmaf-v1",
    hardwareContext: { environmentId: "env-apple-m2", environmentFingerprint: "envfp-apple-m2", cpuModel: "Apple M2", gpuModel: "", ramGB: 16, os: "macOS 15" },
    sampleCount: 4,
    avgFps,
    avgVmaf,
    avgVmafP5,
    avgSsim: 0.97,
    avgPsnr: 40,
    avgSizeBytes: Math.round(avgVideoBitrateBps * 10),
    avgVideoBitrateBps,
    avgSourceFps: 30,
    avgPowerW: 48.5,
    fpsPerWatt: Number((avgFps / 48.5).toFixed(4)),
    qualityPerWatt: Number((avgVmaf / 48.5).toFixed(4)),
    plScore,
    plScoreVersion: "7.0",
    plScoreComponents: components,
    plScoreWorkloadId: "mixed-1080p",
    plScoreContext: { formulaVersion: "7.0", benchmarkProtocolVersion: "benchmark-protocol-v1", sourceSuiteVersion: "encodingdb-test-suite-v1", qualityModelId: "vmaf-v1", referenceContextVersion: "reference-frontier-v1", workloadReferenceBitrateBps: 5_000_000, qualityExponent: 2.4, speedCurveRate: 1.2, speedSaturationRealtime: 4 },
    evidence: { evidenceTier: "LOW", provisional: false, eligibleForDefaultRecommendation: true, confidence: { available: false, lower: null, upper: null, width: null, unavailableReason: "Confidence interval unavailable for this aggregate scope." } },
    pareto: { available: true, efficient: true, frontierRank: 0, dominatorRowIds: [], dominatedRowIds: [], unavailableReason: null, canonical: components },
    bdRate: recommended ? { available: false, valuePercent: null, versusRowId: rowId, versusLabel: `${encoderName} ${preset}`, method: null, matchedPointCount: 0, overlapQualityRange: null, unavailableReason: "Reference curve is the selected row itself." } : { available: true, valuePercent: -8.4, versusRowId: "row-balanced", versusLabel: "hevc_videotoolbox medium", method: "piecewise-log-linear", matchedPointCount: 4, overlapQualityRange: [92.4, 95.8] as [number, number], unavailableReason: null },
    fit: { selectedMode: "balanced", modes, recommended, recommendationReason: recommended ? "Best eligible PL Fit result after hard constraints, evidence gating, and Pareto ordering." : null },
    ...overrides,
  });

  const rows = [
    makeRow("row-balanced", "hevc_videotoolbox", "hevc", "medium", 122.4, 94.8, 94.0, 4_800_000, 76.4421, { quality: 0.842, bitrate: 0.51, speed: 0.99 }, false, fitModes(
      { balanced: 80.3, quality: 83.2, storage: 76.1, realtime: 90.5, custom: 80.3 },
      { balanced: 2, quality: 2, storage: 2, realtime: 2, custom: 2 },
      { balanced: true, quality: true, storage: true, realtime: true, custom: true },
    )),
    makeRow("row-quality", "libx265", "hevc", "slow", 36.2, 97.1, 96.2, 5_400_000, 74.981, { quality: 0.93, bitrate: 0.48, speed: 0.71 }, true, fitModes(
      { balanced: 82.4, quality: 89.7, storage: null, realtime: null, custom: 82.4 },
      { balanced: 1, quality: 1, storage: 4, realtime: 4, custom: 1 },
      { balanced: true, quality: true, storage: false, realtime: false, custom: true },
      { storage: ["Needs bitrate <= 5000000 bps."], realtime: ["Needs realtime ratio >= 1."] },
    ), { fit: { selectedMode: "balanced", modes: fitModes(
      { balanced: 82.4, quality: 89.7, storage: null, realtime: null, custom: 82.4 },
      { balanced: 1, quality: 1, storage: 4, realtime: 4, custom: 1 },
      { balanced: true, quality: true, storage: false, realtime: false, custom: true },
      { storage: ["Needs bitrate <= 5000000 bps."], realtime: ["Needs realtime ratio >= 1."] },
    ), recommended: true, recommendationReason: "Best eligible PL Fit result after hard constraints, evidence gating, and Pareto ordering." } }),
    makeRow("row-storage", "av1_qsv", "av1", "balanced", 54.5, 92.9, 92.0, 3_100_000, 73.118, { quality: 0.79, bitrate: 0.62, speed: 0.83 }, false, fitModes(
      { balanced: 77.4, quality: null, storage: 86.2, realtime: 69.3, custom: 77.4 },
      { balanced: 3, quality: 3, storage: 1, realtime: 3, custom: 3 },
      { balanced: true, quality: false, storage: true, realtime: true, custom: true },
      { quality: ["Needs effective quality >= 94."] },
    ), { fit: { selectedMode: "balanced", modes: fitModes(
      { balanced: 77.4, quality: null, storage: 86.2, realtime: 69.3, custom: 77.4 },
      { balanced: 3, quality: 3, storage: 1, realtime: 3, custom: 3 },
      { balanced: true, quality: false, storage: true, realtime: true, custom: true },
      { quality: ["Needs effective quality >= 94."] },
    ), recommended: false, recommendationReason: "Evidence remains provisional for default recommendation use." }, evidence: { evidenceTier: "PROVISIONAL", provisional: true, eligibleForDefaultRecommendation: false, confidence: { available: false, lower: null, upper: null, width: null, unavailableReason: "Confidence interval unavailable for this aggregate scope." } } }),
    makeRow("row-realtime", "h264_nvenc", "h264", "p6", 196.8, 91.4, 89.7, 5_600_000, 72.901, { quality: 0.74, bitrate: 0.47, speed: 1 }, false, fitModes(
      { balanced: 75.1, quality: null, storage: null, realtime: 94.4, custom: 75.1 },
      { balanced: 4, quality: 4, storage: 3, realtime: 1, custom: 4 },
      { balanced: true, quality: false, storage: false, realtime: true, custom: true },
      { quality: ["Needs effective quality >= 94."], storage: ["Needs bitrate <= 5000000 bps."] },
    ), { pareto: { available: true, efficient: false, frontierRank: 1, dominatorRowIds: ["row-balanced"], dominatedRowIds: [], unavailableReason: null, canonical: { quality: 0.74, bitrate: 0.47, speed: 1 } }, fit: { selectedMode: "balanced", modes: fitModes(
      { balanced: 75.1, quality: null, storage: null, realtime: 94.4, custom: 75.1 },
      { balanced: 4, quality: 4, storage: 3, realtime: 1, custom: 4 },
      { balanced: true, quality: false, storage: false, realtime: true, custom: true },
      { quality: ["Needs effective quality >= 94."], storage: ["Needs bitrate <= 5000000 bps."] },
    ), recommended: false, recommendationReason: null } }),
  ];

  return {
    selectedMode: "balanced",
    profiles,
    rows,
    recommendation: {
      rowId: "row-quality",
      label: "libx265 slow",
      reason: "Best eligible PL Fit result after hard constraints, evidence gating, and Pareto ordering.",
    },
    environmentScope: {
      selectedEnvironmentId: "env-apple-m2",
      selectedEnvironmentFingerprint: "envfp-apple-m2",
      exact: true,
      available: [{ environmentId: "env-apple-m2", environmentFingerprint: "envfp-apple-m2", cpuModel: "Apple M2", gpuModel: "", ramGB: 16, os: "macOS 15", label: "Apple M2 / CPU-only / macOS 15" }],
    },
  };
}

export function buildMockHardware() {
  return [
    {
      cpuModel: "Apple M2",
      gpuModel: "",
      encoderName: "hevc_videotoolbox",
      codecFamily: "hevc",
      preset: "medium",
      rateControl: { requestedMode: "TARGET_BITRATE", effectiveMode: "TARGET_BITRATE", qualityValue: null, targetBitrateKbps: 4800, maxBitrateKbps: null, bufferSizeKbits: null, label: "TARGET_BITRATE 4800 kbps" },
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 80.2,
      avgVmaf: 92.4,
      avgPowerW: 48.5,
      fpsPerWatt: 1.65,
      score: 0.93,
    },
    {
      cpuModel: "Intel Core i7-12700K",
      gpuModel: "NVIDIA GeForce RTX 3060",
      encoderName: "h264_nvenc",
      codecFamily: "h264",
      preset: "p6",
      rateControl: { requestedMode: "CONSTANT_QUALITY", effectiveMode: "CONSTANT_QUALITY", qualityValue: 24, targetBitrateKbps: null, maxBitrateKbps: null, bufferSizeKbits: null, label: "CONSTANT_QUALITY 24" },
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 120.5,
      avgVmaf: 95.2,
      avgPowerW: 160.4,
      fpsPerWatt: 0.75,
      score: 0.76,
    },
  ];
}

export function buildMockEncoders() {
  return [
    {
      encoderName: "h264_nvenc",
      codecFamily: "h264",
      preset: "p6",
      rateControl: { requestedMode: "CONSTANT_QUALITY", effectiveMode: "CONSTANT_QUALITY", qualityValue: 24, targetBitrateKbps: null, maxBitrateKbps: null, bufferSizeKbits: null, label: "CONSTANT_QUALITY 24" },
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 120.5,
      avgVmaf: 95.2,
      avgSsim: 0.9811,
      avgPsnr: 41.8,
      avgSizeBytes: 85 * 1024 * 1024,
    },
    {
      encoderName: "hevc_videotoolbox",
      codecFamily: "hevc",
      preset: "medium",
      rateControl: { requestedMode: "TARGET_BITRATE", effectiveMode: "TARGET_BITRATE", qualityValue: null, targetBitrateKbps: 4800, maxBitrateKbps: null, bufferSizeKbits: null, label: "TARGET_BITRATE 4800 kbps" },
      contentClass: "mixed",
      resolution: "1080p",
      passes: 1,
      sampleCount: 3,
      avgFps: 80.2,
      avgVmaf: 92.4,
      avgSsim: 0.9725,
      avgPsnr: 39.6,
      avgSizeBytes: 70 * 1024 * 1024,
    },
  ];
}
