name: API Smoke Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  smoke:
    if: ${{ secrets.API_BASE_URL != '' }}
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup curl and jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check required secrets
        run: |
          set -euo pipefail
          if [ -z "${API_BASE_URL:-}" ]; then
            echo "Missing secret API_BASE_URL, skipping job." >&2
            exit 0
          fi
          echo "API_BASE_URL is set"

      - name: Health check
        run: |
          set -euo pipefail
          curl -fsSL "$API_BASE_URL/health/ready" | jq .

      - name: Query should return JSON array
        run: |
          set -euo pipefail
          curl -fsSL "$API_BASE_URL/query" | jq -e 'type == "array"' >/dev/null

      - name: Submit sample (optional)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          set -euo pipefail
          payload=$(jq -nc '{
            cpuModel: "CI Runner",
            gpuModel: null,
            ramGB: 4,
            os: "ubuntu",
            codec: "h264",
            preset: "medium",
            fps: 1.23,
            vmaf: 90,
            fileSizeBytes: 12345,
            notes: "smoke"
          }')
          curl -fsSL -X POST "$API_BASE_URL/submit" \
            -H "Content-Type: application/json" \
            -d "$payload" | jq .

      - name: API Hardening (non-destructive)
        run: bash scripts/api_hardening_test.sh
        env:
          ALLOW_MUTATION_REMOTE: '0'


