name: backend-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hardening:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install curl, jq, python3
        run: sudo apt-get update && sudo apt-get install -y curl jq python3

      - name: Copy env
        run: cp env.example .env && sed -i 's/CORS_ORIGIN=.*/CORS_ORIGIN=http:\/\/localhost:3000/' .env && sed -i 's/RATE_LIMIT_MAX=.*/RATE_LIMIT_MAX=50/' .env

      - name: Build and start services
        run: docker compose -f docker-compose.prod.yml build && docker compose -f docker-compose.prod.yml up -d

      - name: Wait for readiness
        run: |
          for i in $(seq 1 60); do
            if curl -sf http://localhost:3001/health/ready >/dev/null; then exit 0; fi
            sleep 1
          done
          docker compose -f docker-compose.prod.yml logs server
          exit 1

      - name: Run hardening tests
        run: bash scripts/api_hardening_test.sh
        env:
          API_BASE_URL: http://localhost:3001
          ALLOW_MUTATION_REMOTE: '0'

      - name: Compose logs on failure
        if: failure()
        run: docker compose -f docker-compose.prod.yml logs --no-color

