name: Build & Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: frontend
        run: npm ci
      - name: Build
        working-directory: frontend
        run: npm run build

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: server
        run: npm ci
      - name: Typecheck
        working-directory: server
        run: npx tsc --noEmit
      - name: Build
        working-directory: server
        run: npm run build

